### ISSUE TITLE
a culprit of emptiness is not documented

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#82]
##### ISSUE TYPE
 - Documentation Report

##### ROLE VERSION

```

```

##### SUMMARY

when you test a variable, and its value is a string, recent `ansible` throws a cryptic error.

```
    The conditional check 'test' failed. The error was: expected token 'end
    of statement block', got '...'
```

##### STEPS TO REPRODUCE

here is an excerpt from `ansible-role-fluentd`, where `fluentd_ca_key` is a string

```yaml
- name: Install ca_key.pem
  template:
    src: ca_key.pem.j2
    dest: "{{ fluentd_certs_dir }}/ca_key.pem"
    mode: 0440
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    validate: openssl rsa -check -noout -passin env:FLUENTD_CA_PASS -in %s
  environment:
    FLUENTD_CA_PASS: "{{ fluentd_ca_private_key_passphrase }}"
  when: fluentd_ca_key
```

the task will throw an error on trombik/ansible-centos-7.2-x86_64:

```
The conditional check 'fluentd_ca_key' failed. The error was: expected token 'end of statement block', got 'RSA'
```

##### EXPECTED RESULTS

as stated in [a comment](https://github.com/ansible/ansible/issues/20392#issuecomment-280430379), the variable should be tested with `is defined`, which should be documented.

##### ACTUAL RESULTS

the culprit is not documented.
